# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendor-search/branch/branch.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vendor-search/branch/branch.proto", :syntax => :proto3) do
    add_message "Branch" do
      optional :metadata, :message, 1, "Branch.Metadata"
      optional :id, :uint32, 2
      optional :restaurant_id, :uint32, 3
      optional :local_id, :uint32, 4
      optional :location, :message, 5, "Branch.Location"
      optional :created_at, :message, 6, "google.protobuf.Timestamp"
      optional :updated_at, :message, 7, "google.protobuf.Timestamp"
      optional :enabled, :bool, 8
      optional :defaultstatus, :uint32, 9
      optional :branchtype, :uint32, 10
      optional :pickup, :bool, 11
      optional :working_time_id, :uint32, 12
      optional :printer_id, :uint32, 13
      optional :accept_credit_card, :bool, 14
      optional :company_id, :uint32, 15
      optional :public_phone_number, :uint32, 16
      optional :follow_up_minutes, :uint32, 17
      optional :billing_group_id, :uint32, 18
      optional :accept_cash_on_delivery, :bool, 19
      optional :menu_id, :uint32, 20
      optional :sub_working_time_id, :uint32, 21
      optional :deliver_using_map, :bool, 22
      optional :accept_voucher, :bool, 23
      optional :reference_id, :string, 24
      optional :reference_name, :string, 25
      optional :reference_name_ar, :string, 26
      optional :grade, :double, 27
      optional :delivery_provider, :uint32, 28
      optional :hello_food_vendor_code, :uint32, 29
      optional :own_delivery_condition_group_id, :uint32, 30
      optional :payment_at_restaurant, :bool, 31
      optional :link_token, :uint32, 32
      optional :dont_accept_cash, :bool, 33
      optional :exclude_from_penalty, :bool, 34
      optional :pay_by_transmitter, :bool, 35
      optional :enabled_reason, :uint32, 36
      optional :super_eta, :uint32, 37
      optional :pay_later, :bool, 38
      optional :pay_at_delivery_enabled, :bool, 39
      optional :salesforce_grid, :uint32, 40
      optional :status_updated_at, :message, 41, "google.protobuf.Timestamp"
      optional :current_status, :uint32, 42
      optional :salesforce_id, :uint32, 43
      optional :sf_account_reference_id, :uint32, 44
      optional :disable_order_note, :bool, 45
      optional :commission_base, :uint32, 46
      optional :finance_specefication, :uint32, 47
      optional :company_bank_account_id, :uint32, 48
      optional :is_new, :bool, 49
      optional :preferred_language, :uint32, 50
    end
    add_message "Branch.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "Branch.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "Branch.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
    add_message "Branch.Location" do
      optional :latitude, :double, 1
      optional :longitude, :double, 2
    end
  end
end

Branch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Branch").msgclass
Branch::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Branch.Metadata").msgclass
Branch::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Branch.Metadata.ActionType").enummodule
Branch::Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Branch.Location").msgclass
