# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offer/offer.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("offer/offer.proto", :syntax => :proto3) do
    add_message "Offer" do
      optional :metadata, :message, 1, "Offer.Metadata"
      optional :id, :uint32, 2
      optional :branch_id, :uint32, 3
      optional :offer_id, :uint32, 4
      optional :offer_weight, :uint32, 5
      optional :offer_data, :string, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "Offer.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "Offer.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "Offer.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      Offer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Offer").msgclass
      Offer::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Offer.Metadata").msgclass
      Offer::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Offer.Metadata.ActionType").enummodule
    end
  end
end
