# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant-link-kitchen/restaurant-link-kitchen.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("restaurant-link-kitchen/restaurant-link-kitchen.proto", :syntax => :proto3) do
    add_message "RestaurantLinkKitchen" do
      optional :metadata, :message, 1, "RestaurantLinkKitchen.Metadata"
      optional :id, :uint32, 2
      optional :restaurant_id, :uint32, 3
      optional :kitchen_id, :uint32, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :updated_at, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "RestaurantLinkKitchen.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "RestaurantLinkKitchen.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "RestaurantLinkKitchen.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      RestaurantLinkKitchen = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RestaurantLinkKitchen").msgclass
      RestaurantLinkKitchen::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RestaurantLinkKitchen.Metadata").msgclass
      RestaurantLinkKitchen::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RestaurantLinkKitchen.Metadata.ActionType").enummodule
    end
  end
end
