// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: protobuf/vendor-search/week-time-rule/week-time-rule.proto

package week_time_rule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeekTimeRule_Metadata_ActionType int32

const (
	WeekTimeRule_Metadata_CREATE WeekTimeRule_Metadata_ActionType = 0
	WeekTimeRule_Metadata_UPDATE WeekTimeRule_Metadata_ActionType = 1
	WeekTimeRule_Metadata_DELETE WeekTimeRule_Metadata_ActionType = 2
)

// Enum value maps for WeekTimeRule_Metadata_ActionType.
var (
	WeekTimeRule_Metadata_ActionType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	WeekTimeRule_Metadata_ActionType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x WeekTimeRule_Metadata_ActionType) Enum() *WeekTimeRule_Metadata_ActionType {
	p := new(WeekTimeRule_Metadata_ActionType)
	*p = x
	return p
}

func (x WeekTimeRule_Metadata_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeekTimeRule_Metadata_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_enumTypes[0].Descriptor()
}

func (WeekTimeRule_Metadata_ActionType) Type() protoreflect.EnumType {
	return &file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_enumTypes[0]
}

func (x WeekTimeRule_Metadata_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeekTimeRule_Metadata_ActionType.Descriptor instead.
func (WeekTimeRule_Metadata_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescGZIP(), []int{0, 0, 0}
}

type WeekTimeRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata     *WeekTimeRule_Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id           uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RestaurantId uint32                 `protobuf:"varint,4,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *WeekTimeRule) Reset() {
	*x = WeekTimeRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeekTimeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeekTimeRule) ProtoMessage() {}

func (x *WeekTimeRule) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeekTimeRule.ProtoReflect.Descriptor instead.
func (*WeekTimeRule) Descriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescGZIP(), []int{0}
}

func (x *WeekTimeRule) GetMetadata() *WeekTimeRule_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WeekTimeRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeekTimeRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeekTimeRule) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *WeekTimeRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WeekTimeRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WeekTimeRule_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid           string                           `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Source         string                           `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Action         WeekTimeRule_Metadata_ActionType `protobuf:"varint,3,opt,name=action,proto3,enum=WeekTimeRule_Metadata_ActionType" json:"action,omitempty"`
	EventTimestamp *timestamppb.Timestamp           `protobuf:"bytes,4,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
}

func (x *WeekTimeRule_Metadata) Reset() {
	*x = WeekTimeRule_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeekTimeRule_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeekTimeRule_Metadata) ProtoMessage() {}

func (x *WeekTimeRule_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeekTimeRule_Metadata.ProtoReflect.Descriptor instead.
func (*WeekTimeRule_Metadata) Descriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WeekTimeRule_Metadata) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *WeekTimeRule_Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WeekTimeRule_Metadata) GetAction() WeekTimeRule_Metadata_ActionType {
	if x != nil {
		return x.Action
	}
	return WeekTimeRule_Metadata_CREATE
}

func (x *WeekTimeRule_Metadata) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

var File_protobuf_vendor_search_week_time_rule_week_time_rule_proto protoreflect.FileDescriptor

var file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x77, 0x65, 0x65, 0x6b, 0x2d, 0x74, 0x69,
	0x6d, 0x65, 0x2d, 0x72, 0x75, 0x6c, 0x65, 0x2f, 0x77, 0x65, 0x65, 0x6b, 0x2d, 0x74, 0x69, 0x6d,
	0x65, 0x2d, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x03,
	0x0a, 0x0c, 0x57, 0x65, 0x65, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x32,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x1a, 0xe8, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x57, 0x65, 0x65,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x30, 0x0a, 0x0a, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x42, 0x2d, 0x5a, 0x2b,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x77, 0x65,
	0x65, 0x6b, 0x2d, 0x74, 0x69, 0x6d, 0x65, 0x2d, 0x72, 0x75, 0x6c, 0x65, 0x3b, 0x77, 0x65, 0x65,
	0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescOnce sync.Once
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescData = file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDesc
)

func file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescGZIP() []byte {
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescOnce.Do(func() {
		file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescData)
	})
	return file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDescData
}

var file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_goTypes = []interface{}{
	(WeekTimeRule_Metadata_ActionType)(0), // 0: WeekTimeRule.Metadata.ActionType
	(*WeekTimeRule)(nil),                  // 1: WeekTimeRule
	(*WeekTimeRule_Metadata)(nil),         // 2: WeekTimeRule.Metadata
	(*timestamppb.Timestamp)(nil),         // 3: google.protobuf.Timestamp
}
var file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_depIdxs = []int32{
	2, // 0: WeekTimeRule.metadata:type_name -> WeekTimeRule.Metadata
	3, // 1: WeekTimeRule.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: WeekTimeRule.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: WeekTimeRule.Metadata.action:type_name -> WeekTimeRule.Metadata.ActionType
	3, // 4: WeekTimeRule.Metadata.event_timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_init() }
func file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_init() {
	if File_protobuf_vendor_search_week_time_rule_week_time_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeekTimeRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeekTimeRule_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_goTypes,
		DependencyIndexes: file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_depIdxs,
		EnumInfos:         file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_enumTypes,
		MessageInfos:      file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_msgTypes,
	}.Build()
	File_protobuf_vendor_search_week_time_rule_week_time_rule_proto = out.File
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_rawDesc = nil
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_goTypes = nil
	file_protobuf_vendor_search_week_time_rule_week_time_rule_proto_depIdxs = nil
}
