# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification/sms/sms.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification/sms/sms.proto", :syntax => :proto3) do
    add_message "notification.sms.Request" do
      optional :guid, :string, 1
      optional :title, :string, 2
      optional :source, :string, 3
      optional :recipient, :string, 4
      optional :sms_type, :enum, 5, "notification.sms.Request.SmsType"
      map :payload, :string, :string, 6
      optional :event_timestamp, :message, 7, "google.protobuf.Timestamp"
    end
    add_enum "notification.sms.Request.SmsType" do
      value :DEFAULT, 0
      value :URGENT, 1
      value :BACKUP, 2
    end
    add_message "notification.sms.Response" do
      optional :error, :string, 1
    end
  end
end

module Notification
  module Sms
    Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.sms.Request").msgclass
    Request::SmsType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.sms.Request.SmsType").enummodule
    Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.sms.Response").msgclass
  end
end
