// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: protobuf/vendor-search/cutback/cutback.proto

package cutback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cutback_Metadata_ActionType int32

const (
	Cutback_Metadata_CREATE Cutback_Metadata_ActionType = 0
	Cutback_Metadata_UPDATE Cutback_Metadata_ActionType = 1
	Cutback_Metadata_DELETE Cutback_Metadata_ActionType = 2
)

// Enum value maps for Cutback_Metadata_ActionType.
var (
	Cutback_Metadata_ActionType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	Cutback_Metadata_ActionType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x Cutback_Metadata_ActionType) Enum() *Cutback_Metadata_ActionType {
	p := new(Cutback_Metadata_ActionType)
	*p = x
	return p
}

func (x Cutback_Metadata_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cutback_Metadata_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_vendor_search_cutback_cutback_proto_enumTypes[0].Descriptor()
}

func (Cutback_Metadata_ActionType) Type() protoreflect.EnumType {
	return &file_protobuf_vendor_search_cutback_cutback_proto_enumTypes[0]
}

func (x Cutback_Metadata_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cutback_Metadata_ActionType.Descriptor instead.
func (Cutback_Metadata_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_cutback_cutback_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Cutback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata                      *Cutback_Metadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id                            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	CutbackAmount                 float32                `protobuf:"fixed32,3,opt,name=cutback_amount,json=cutbackAmount,proto3" json:"cutback_amount,omitempty"`
	Minimum                       float32                `protobuf:"fixed32,4,opt,name=minimum,proto3" json:"minimum,omitempty"`
	CreatedAt                     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Percentage                    float64                `protobuf:"fixed64,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	OfferId                       uint32                 `protobuf:"varint,8,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	DeliveryFeePercentageDiscount uint32                 `protobuf:"varint,9,opt,name=delivery_fee_percentage_discount,json=deliveryFeePercentageDiscount,proto3" json:"delivery_fee_percentage_discount,omitempty"`
	Maximum                       float32                `protobuf:"fixed32,10,opt,name=maximum,proto3" json:"maximum,omitempty"`
	DeliveryFeeFixedDiscount      float64                `protobuf:"fixed64,11,opt,name=delivery_fee_fixed_discount,json=deliveryFeeFixedDiscount,proto3" json:"delivery_fee_fixed_discount,omitempty"`
}

func (x *Cutback) Reset() {
	*x = Cutback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cutback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cutback) ProtoMessage() {}

func (x *Cutback) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cutback.ProtoReflect.Descriptor instead.
func (*Cutback) Descriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_cutback_cutback_proto_rawDescGZIP(), []int{0}
}

func (x *Cutback) GetMetadata() *Cutback_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Cutback) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cutback) GetCutbackAmount() float32 {
	if x != nil {
		return x.CutbackAmount
	}
	return 0
}

func (x *Cutback) GetMinimum() float32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *Cutback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cutback) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Cutback) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Cutback) GetOfferId() uint32 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

func (x *Cutback) GetDeliveryFeePercentageDiscount() uint32 {
	if x != nil {
		return x.DeliveryFeePercentageDiscount
	}
	return 0
}

func (x *Cutback) GetMaximum() float32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *Cutback) GetDeliveryFeeFixedDiscount() float64 {
	if x != nil {
		return x.DeliveryFeeFixedDiscount
	}
	return 0
}

type Cutback_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid           string                      `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Source         string                      `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Action         Cutback_Metadata_ActionType `protobuf:"varint,3,opt,name=action,proto3,enum=Cutback_Metadata_ActionType" json:"action,omitempty"`
	EventTimestamp *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
}

func (x *Cutback_Metadata) Reset() {
	*x = Cutback_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cutback_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cutback_Metadata) ProtoMessage() {}

func (x *Cutback_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cutback_Metadata.ProtoReflect.Descriptor instead.
func (*Cutback_Metadata) Descriptor() ([]byte, []int) {
	return file_protobuf_vendor_search_cutback_cutback_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Cutback_Metadata) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Cutback_Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Cutback_Metadata) GetAction() Cutback_Metadata_ActionType {
	if x != nil {
		return x.Action
	}
	return Cutback_Metadata_CREATE
}

func (x *Cutback_Metadata) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

var File_protobuf_vendor_search_cutback_cutback_proto protoreflect.FileDescriptor

var file_protobuf_vendor_search_cutback_cutback_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x63, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b,
	0x2f, 0x63, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc2, 0x05, 0x0a, 0x07, 0x43, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x43, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75,
	0x74, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0d, 0x63, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x20,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x1d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12,
	0x3d, 0x0a, 0x1b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x66, 0x65, 0x65, 0x5f,
	0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x18, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65,
	0x65, 0x46, 0x69, 0x78, 0x65, 0x64, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xe3,
	0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x43, 0x75, 0x74, 0x62, 0x61, 0x63,
	0x6b, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a,
	0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x30, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x02, 0x42, 0x1f, 0x5a, 0x1d, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2d, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x63, 0x75, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x3b, 0x63, 0x75,
	0x74, 0x62, 0x61, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_vendor_search_cutback_cutback_proto_rawDescOnce sync.Once
	file_protobuf_vendor_search_cutback_cutback_proto_rawDescData = file_protobuf_vendor_search_cutback_cutback_proto_rawDesc
)

func file_protobuf_vendor_search_cutback_cutback_proto_rawDescGZIP() []byte {
	file_protobuf_vendor_search_cutback_cutback_proto_rawDescOnce.Do(func() {
		file_protobuf_vendor_search_cutback_cutback_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_vendor_search_cutback_cutback_proto_rawDescData)
	})
	return file_protobuf_vendor_search_cutback_cutback_proto_rawDescData
}

var file_protobuf_vendor_search_cutback_cutback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_vendor_search_cutback_cutback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_vendor_search_cutback_cutback_proto_goTypes = []interface{}{
	(Cutback_Metadata_ActionType)(0), // 0: Cutback.Metadata.ActionType
	(*Cutback)(nil),                  // 1: Cutback
	(*Cutback_Metadata)(nil),         // 2: Cutback.Metadata
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_protobuf_vendor_search_cutback_cutback_proto_depIdxs = []int32{
	2, // 0: Cutback.metadata:type_name -> Cutback.Metadata
	3, // 1: Cutback.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: Cutback.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: Cutback.Metadata.action:type_name -> Cutback.Metadata.ActionType
	3, // 4: Cutback.Metadata.event_timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_vendor_search_cutback_cutback_proto_init() }
func file_protobuf_vendor_search_cutback_cutback_proto_init() {
	if File_protobuf_vendor_search_cutback_cutback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cutback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_vendor_search_cutback_cutback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cutback_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_vendor_search_cutback_cutback_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_vendor_search_cutback_cutback_proto_goTypes,
		DependencyIndexes: file_protobuf_vendor_search_cutback_cutback_proto_depIdxs,
		EnumInfos:         file_protobuf_vendor_search_cutback_cutback_proto_enumTypes,
		MessageInfos:      file_protobuf_vendor_search_cutback_cutback_proto_msgTypes,
	}.Build()
	File_protobuf_vendor_search_cutback_cutback_proto = out.File
	file_protobuf_vendor_search_cutback_cutback_proto_rawDesc = nil
	file_protobuf_vendor_search_cutback_cutback_proto_goTypes = nil
	file_protobuf_vendor_search_cutback_cutback_proto_depIdxs = nil
}
