# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cutback/cutback.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cutback/cutback.proto", :syntax => :proto3) do
    add_message "Cutback" do
      optional :metadata, :message, 1, "Cutback.Metadata"
      optional :id, :uint32, 2
      optional :cutback_amount, :float, 3
      optional :minimum, :float, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :updated_at, :message, 6, "google.protobuf.Timestamp"
      optional :percentage, :double, 7
      optional :offer_id, :uint32, 8
      optional :delivery_fee_percentage_discount, :uint32, 9
      optional :maximum, :float, 10
      optional :delivery_fee_fixed_discount, :double, 11
    end
    add_message "Cutback.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "Cutback.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "Cutback.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      Cutback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Cutback").msgclass
      Cutback::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Cutback.Metadata").msgclass
      Cutback::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Cutback.Metadata.ActionType").enummodule
    end
  end
end
