# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home-module/home-module.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("home-module/home-module.proto", :syntax => :proto3) do
    add_message "HomeModule" do
      optional :metadata, :message, 1, "HomeModule.Metadata"
      optional :id, :uint32, 2
      optional :slug, :string, 3
      optional :redirection, :uint32, 4
      optional :enabled, :bool, 5
      optional :weight, :uint32, 6
      optional :render_filter, :bool, 7
      optional :swimlane_config, :string, 8
      optional :title, :string, 9
      optional :title_ar, :string, 10
      optional :description, :string, 11
      optional :cover_image_url, :string, 12
      optional :disabled_cover_image_url, :string, 13
      optional :created_at, :message, 14, "google.protobuf.Timestamp"
      optional :updated_at, :message, 15, "google.protobuf.Timestamp"
      repeated :configs, :string, 16
    end
    add_message "HomeModule.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "HomeModule.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "HomeModule.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      HomeModule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule").msgclass
      HomeModule::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule.Metadata").msgclass
      HomeModule::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule.Metadata.ActionType").enummodule
    end
  end
end
