# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendor-search/home-module/home-module.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vendor-search/home-module/home-module.proto", :syntax => :proto3) do
    add_message "HomeModule" do
      optional :metadata, :message, 1, "HomeModule.Metadata"
      optional :id, :uint32, 2
      optional :slug, :string, 3
      optional :redirection, :uint32, 4
      optional :enabled, :bool, 5
      optional :weight, :sint32, 6
      optional :render_filter, :bool, 7
      optional :swimlane_config, :string, 8
      optional :title, :string, 9
      optional :title_ar, :string, 10
      optional :description, :string, 11
      optional :cover_image_3x2_url, :string, 12
      optional :cover_image_3x3_url, :string, 13
      optional :cover_image_4x3_url, :string, 14
      optional :cover_image_4x4_url, :string, 15
      optional :cover_image_7x2_url, :string, 16
      optional :cover_image_7x3_url, :string, 17
      optional :cover_image_7x4_url, :string, 18
      optional :disabled_cover_image_3x2_url, :string, 19
      optional :disabled_cover_image_3x3_url, :string, 20
      optional :disabled_cover_image_4x3_url, :string, 21
      optional :disabled_cover_image_4x4_url, :string, 22
      optional :disabled_cover_image_7x2_url, :string, 23
      optional :disabled_cover_image_7x3_url, :string, 24
      optional :disabled_cover_image_7x4_url, :string, 25
      optional :created_at, :message, 26, "google.protobuf.Timestamp"
      optional :updated_at, :message, 27, "google.protobuf.Timestamp"
      repeated :configs, :string, 28
    end
    add_message "HomeModule.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "HomeModule.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "HomeModule.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module PubsubSynchronizer
  module Protobufs
    module Protos
      HomeModule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule").msgclass
      HomeModule::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule.Metadata").msgclass
      HomeModule::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModule.Metadata.ActionType").enummodule
    end
  end
end
