# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification/push/ios/ios.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification/push/ios/ios.proto", :syntax => :proto3) do
    add_message "protos.notification.push.ios.Request" do
      optional :guid, :string, 1
      optional :title, :string, 2
      optional :source, :string, 3
      repeated :tokens, :string, 4
      optional :payload, :message, 5, "protos.notification.push.ios.Request.Message"
      optional :event_timestamp, :message, 6, "google.protobuf.Timestamp"
      optional :service_token, :string, 7
    end
    add_message "protos.notification.push.ios.Request.Message" do
      optional :topic, :string, 1
      optional :collapse_id, :string, 2
      map :custom, :string, :string, 3
      optional :priority, :enum, 4, "protos.notification.push.ios.Request.Priority"
      optional :alert, :string, 5
      optional :sound, :string, 6
    end
    add_enum "protos.notification.push.ios.Request.Priority" do
      value :LOW, 0
      value :HIGH, 1
    end
    add_message "protos.notification.push.ios.Response" do
      optional :error, :string, 1
    end
  end
end

module Protos
  module Notification
    module Push
      module Ios
        Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.ios.Request").msgclass
        Request::Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.ios.Request.Message").msgclass
        Request::Priority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.ios.Request.Priority").enummodule
        Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.ios.Response").msgclass
      end
    end
  end
end
