# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: branch-reviews-summary/branch-reviews-summary.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("branch-reviews-summary/branch-reviews-summary.proto", :syntax => :proto3) do
    add_message "BranchReviewsSummary" do
      optional :metadata, :message, 1, "BranchReviewsSummary.Metadata"
      optional :id, :uint32, 2
      optional :branch_id, :uint32, 3
      optional :restaurant_id, :uint32, 4
      optional :mean_rate, :float, 5
      optional :reviews_count, :uint32, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "BranchReviewsSummary.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "BranchReviewsSummary.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "BranchReviewsSummary.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      BranchReviewsSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BranchReviewsSummary").msgclass
      BranchReviewsSummary::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BranchReviewsSummary.Metadata").msgclass
      BranchReviewsSummary::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BranchReviewsSummary.Metadata.ActionType").enummodule
    end
  end
end
