// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: vendor-search/branch-reviews-summary/branch-reviews-summary.proto

package branch_reviews_summary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BranchReviewsSummary_Metadata_ActionType int32

const (
	BranchReviewsSummary_Metadata_CREATE BranchReviewsSummary_Metadata_ActionType = 0
	BranchReviewsSummary_Metadata_UPDATE BranchReviewsSummary_Metadata_ActionType = 1
	BranchReviewsSummary_Metadata_DELETE BranchReviewsSummary_Metadata_ActionType = 2
)

// Enum value maps for BranchReviewsSummary_Metadata_ActionType.
var (
	BranchReviewsSummary_Metadata_ActionType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	BranchReviewsSummary_Metadata_ActionType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x BranchReviewsSummary_Metadata_ActionType) Enum() *BranchReviewsSummary_Metadata_ActionType {
	p := new(BranchReviewsSummary_Metadata_ActionType)
	*p = x
	return p
}

func (x BranchReviewsSummary_Metadata_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BranchReviewsSummary_Metadata_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_enumTypes[0].Descriptor()
}

func (BranchReviewsSummary_Metadata_ActionType) Type() protoreflect.EnumType {
	return &file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_enumTypes[0]
}

func (x BranchReviewsSummary_Metadata_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BranchReviewsSummary_Metadata_ActionType.Descriptor instead.
func (BranchReviewsSummary_Metadata_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescGZIP(), []int{0, 0, 0}
}

type BranchReviewsSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata     *BranchReviewsSummary_Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id           uint32                         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	BranchId     uint32                         `protobuf:"varint,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	RestaurantId uint32                         `protobuf:"varint,4,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	MeanRate     float32                        `protobuf:"fixed32,5,opt,name=mean_rate,json=meanRate,proto3" json:"mean_rate,omitempty"`
	ReviewsCount uint32                         `protobuf:"varint,6,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	CreatedAt    *timestamppb.Timestamp         `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp         `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BranchReviewsSummary) Reset() {
	*x = BranchReviewsSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchReviewsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchReviewsSummary) ProtoMessage() {}

func (x *BranchReviewsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchReviewsSummary.ProtoReflect.Descriptor instead.
func (*BranchReviewsSummary) Descriptor() ([]byte, []int) {
	return file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescGZIP(), []int{0}
}

func (x *BranchReviewsSummary) GetMetadata() *BranchReviewsSummary_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BranchReviewsSummary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BranchReviewsSummary) GetBranchId() uint32 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *BranchReviewsSummary) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *BranchReviewsSummary) GetMeanRate() float32 {
	if x != nil {
		return x.MeanRate
	}
	return 0
}

func (x *BranchReviewsSummary) GetReviewsCount() uint32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

func (x *BranchReviewsSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BranchReviewsSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BranchReviewsSummary_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid           string                                   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Source         string                                   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Action         BranchReviewsSummary_Metadata_ActionType `protobuf:"varint,3,opt,name=action,proto3,enum=BranchReviewsSummary_Metadata_ActionType" json:"action,omitempty"`
	EventTimestamp *timestamppb.Timestamp                   `protobuf:"bytes,4,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
}

func (x *BranchReviewsSummary_Metadata) Reset() {
	*x = BranchReviewsSummary_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchReviewsSummary_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchReviewsSummary_Metadata) ProtoMessage() {}

func (x *BranchReviewsSummary_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchReviewsSummary_Metadata.ProtoReflect.Descriptor instead.
func (*BranchReviewsSummary_Metadata) Descriptor() ([]byte, []int) {
	return file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BranchReviewsSummary_Metadata) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *BranchReviewsSummary_Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BranchReviewsSummary_Metadata) GetAction() BranchReviewsSummary_Metadata_ActionType {
	if x != nil {
		return x.Action
	}
	return BranchReviewsSummary_Metadata_CREATE
}

func (x *BranchReviewsSummary_Metadata) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

var File_vendor_search_branch_reviews_summary_branch_reviews_summary_proto protoreflect.FileDescriptor

var file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDesc = []byte{
	0x0a, 0x41, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x2d, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x2d, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x2d, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x2d, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x04, 0x0a, 0x14, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x3a, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x65, 0x61, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x6d, 0x65, 0x61, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x1a, 0xf0, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x67, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x43, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x30, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x42, 0x3d, 0x5a, 0x3b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x2d, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x2d, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x3b, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x5f, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescOnce sync.Once
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescData = file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDesc
)

func file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescGZIP() []byte {
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescOnce.Do(func() {
		file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescData)
	})
	return file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDescData
}

var file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_goTypes = []interface{}{
	(BranchReviewsSummary_Metadata_ActionType)(0), // 0: BranchReviewsSummary.Metadata.ActionType
	(*BranchReviewsSummary)(nil),                  // 1: BranchReviewsSummary
	(*BranchReviewsSummary_Metadata)(nil),         // 2: BranchReviewsSummary.Metadata
	(*timestamppb.Timestamp)(nil),                 // 3: google.protobuf.Timestamp
}
var file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_depIdxs = []int32{
	2, // 0: BranchReviewsSummary.metadata:type_name -> BranchReviewsSummary.Metadata
	3, // 1: BranchReviewsSummary.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: BranchReviewsSummary.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: BranchReviewsSummary.Metadata.action:type_name -> BranchReviewsSummary.Metadata.ActionType
	3, // 4: BranchReviewsSummary.Metadata.event_timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_init() }
func file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_init() {
	if File_vendor_search_branch_reviews_summary_branch_reviews_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchReviewsSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchReviewsSummary_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_goTypes,
		DependencyIndexes: file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_depIdxs,
		EnumInfos:         file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_enumTypes,
		MessageInfos:      file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_msgTypes,
	}.Build()
	File_vendor_search_branch_reviews_summary_branch_reviews_summary_proto = out.File
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_rawDesc = nil
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_goTypes = nil
	file_vendor_search_branch_reviews_summary_branch_reviews_summary_proto_depIdxs = nil
}
