# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification/push/android/android.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification/push/android/android.proto", :syntax => :proto3) do
    add_message "protos.notification.push.android.Request" do
      optional :guid, :string, 1
      optional :title, :string, 2
      optional :source, :string, 3
      repeated :tokens, :string, 4
      optional :payload, :message, 5, "protos.notification.push.android.Request.Message"
      optional :event_timestamp, :message, 6, "google.protobuf.Timestamp"
      optional :service_token, :string, 7
    end
    add_message "protos.notification.push.android.Request.Message" do
      optional :topic, :string, 1
      optional :collapse_key, :string, 2
      optional :priority, :enum, 3, "protos.notification.push.android.Request.Priority"
      map :data, :string, :string, 4
    end
    add_enum "protos.notification.push.android.Request.Priority" do
      value :NORMAL, 0
      value :HIGH, 1
    end
    add_message "protos.notification.push.android.Response" do
      optional :error, :string, 1
    end
  end
end

module Protos
  module Notification
    module Push
      module Android
        Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.android.Request").msgclass
        Request::Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.android.Request.Message").msgclass
        Request::Priority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.android.Request.Priority").enummodule
        Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.push.android.Response").msgclass
      end
    end
  end
end
