# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home-module-vertical/home-module-vertical.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("home-module-vertical/home-module-vertical.proto", :syntax => :proto3) do
    add_message "HomeModuleVertical" do
      optional :metadata, :message, 1, "HomeModuleVertical.Metadata"
      optional :id, :uint32, 2
      optional :vertical_id, :uint32, 3
      optional :home_module_id, :uint32, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :updated_at, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "HomeModuleVertical.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "HomeModuleVertical.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "HomeModuleVertical.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

module Pubsub
  module Protos
    module VendorSearch
      HomeModuleVertical = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModuleVertical").msgclass
      HomeModuleVertical::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModuleVertical.Metadata").msgclass
      HomeModuleVertical::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HomeModuleVertical.Metadata.ActionType").enummodule
    end
  end
end
