# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendor-search/kitchen/kitchen.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vendor-search/kitchen/kitchen.proto", :syntax => :proto3) do
    add_message "Kitchen" do
      optional :metadata, :message, 1, "Kitchen.Metadata"
      optional :id, :uint32, 2
      optional :name, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :enabled, :bool, 6
      optional :image_url, :string, 7
      optional :name_ar, :string, 8
      optional :slug, :string, 9
      optional :description, :string, 10
      optional :description_ar, :string, 11
      optional :slug_ar, :string, 12
      optional :photo_url, :string, 13
      optional :weight, :uint32, 14
      optional :salesforce_name, :string, 15
    end
    add_message "Kitchen.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "Kitchen.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "Kitchen.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

Kitchen = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Kitchen").msgclass
Kitchen::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Kitchen.Metadata").msgclass
Kitchen::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Kitchen.Metadata.ActionType").enummodule
