# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification/slack/slack.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification/slack/slack.proto", :syntax => :proto3) do
    add_message "protos.notification.slack.Request" do
      optional :guid, :string, 1
      optional :title, :string, 2
      optional :source, :string, 3
      optional :webhook, :string, 4
      optional :level, :enum, 5, "protos.notification.slack.Request.SeverityLevel"
      map :payload, :string, :string, 6
      optional :event_timestamp, :message, 7, "google.protobuf.Timestamp"
    end
    add_enum "protos.notification.slack.Request.SeverityLevel" do
      value :INFO, 0
      value :WARN, 1
      value :ERROR, 2
    end
    add_message "protos.notification.slack.Response" do
      optional :error, :string, 1
    end
  end
end

module Protos
  module Notification
    module Slack
      Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.slack.Request").msgclass
      Request::SeverityLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.slack.Request.SeverityLevel").enummodule
      Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.slack.Response").msgclass
    end
  end
end
