# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/vendor-search/week-time/week-time.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/vendor-search/week-time/week-time.proto", :syntax => :proto3) do
    add_message "WeekTime" do
      optional :metadata, :message, 1, "WeekTime.Metadata"
      optional :id, :uint32, 2
      optional :saturday, :bool, 3
      optional :sunday, :bool, 4
      optional :monday, :bool, 5
      optional :tuesday, :bool, 6
      optional :wednesday, :bool, 7
      optional :thursday, :bool, 8
      optional :friday, :bool, 9
      optional :start_minute, :uint32, 10
      optional :end_minute, :uint32, 11
      optional :weektimerule_id, :uint32, 12
      optional :created_at, :message, 13, "google.protobuf.Timestamp"
      optional :updated_at, :message, 14, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 15, "google.protobuf.Timestamp"
    end
    add_message "WeekTime.Metadata" do
      optional :guid, :string, 1
      optional :source, :string, 2
      optional :action, :enum, 3, "WeekTime.Metadata.ActionType"
      optional :event_timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_enum "WeekTime.Metadata.ActionType" do
      value :CREATE, 0
      value :UPDATE, 1
      value :DELETE, 2
    end
  end
end

WeekTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WeekTime").msgclass
WeekTime::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WeekTime.Metadata").msgclass
WeekTime::Metadata::ActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WeekTime.Metadata.ActionType").enummodule
