# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("email.proto", :syntax => :proto3) do
    add_message "protos.notification.email.Address" do
      optional :name, :string, 1
      optional :email, :string, 2
    end
    add_message "protos.notification.email.Content" do
      optional :message, :string, 2
      map :headers, :string, :string, 3
    end
    add_message "protos.notification.email.Request" do
      optional :guid, :string, 1
      optional :subject, :string, 2
      optional :content, :message, 3, "protos.notification.email.Content"
      optional :from, :message, 4, "protos.notification.email.Address"
      optional :replyTo, :message, 5, "protos.notification.email.Address"
      repeated :to, :message, 6, "protos.notification.email.Address"
      optional :event_timestamp, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "protos.notification.email.Response" do
      optional :error, :string, 1
    end
  end
end

module Protos
  module Notification
    module Email
      Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.email.Address").msgclass
      Content = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.email.Content").msgclass
      Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.email.Request").msgclass
      Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.notification.email.Response").msgclass
    end
  end
end
